# Generated by Django 4.0.10 on 2024-07-16 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255, verbose_name='Единица измерения')),
                ('dateStart', models.DateField(blank=True, verbose_name='Дата начала')),
                ('dateEnd', models.DateField(blank=True, verbose_name='Дата окончания')),
                ('accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
                ('color', models.CharField(blank=True, max_length=255, verbose_name='Цвет')),
                ('year', models.FloatField(default=0, verbose_name='Год')),
                ('isVerified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.indicatorcategory', verbose_name='Категория')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.district', verbose_name='Район')),
                ('graphCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.graphcategory', verbose_name='Категория графов')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.state', verbose_name='Город')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.indicatorsubcategory', verbose_name='Под категория')),
            ],
            options={
                'verbose_name': 'Индикатор',
                'verbose_name_plural': 'Индикаторы',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('image', models.TextField(blank=True, verbose_name='Ссылка на фото')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.TextField(blank=True, verbose_name='Ссылка на фото')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='UsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.TextField(blank=True, verbose_name='Ссылка на фото')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Полезная ссылка',
                'verbose_name_plural': 'Полезные ссылки',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('doc', 'Документ'), ('link', 'Ссылка')], default='link', max_length=25, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('link', models.TextField(blank=True, verbose_name='Ссылка')),
                ('datePublication', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.newscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(blank=True, max_length=255, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.TextField(blank=True, verbose_name='Иконка')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.indicator', verbose_name='Индикатор')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.indicatorsubcategory', verbose_name='Под категория')),
            ],
            options={
                'verbose_name': 'Мета данные',
                'verbose_name_plural': 'Мета данные',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('post', 'Пост'), ('patch', 'Патч'), ('delete', 'Удалить'), ('error', 'Ошибка'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Действия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(blank=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
